language: julia
os:
  - linux
julia:
  - 1.1
notifications:
  email: false
after_success:
  - julia --project -e 'using Pkg, NCEI; cd(dirname(Pkg.pathof(NCEI))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder("."))'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
