site_name:        NCEI.jl
repo_url:         https://github.com/Nosferican/NCEI.jl
site_description: NCEI Docs
site_author:      José Bayoán Santiago Calderón

theme: material

extra_css:
  - assets/Documenter.css

pages:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Walkthrough: Walkthrough.md
